name = "Carnival of Horrors"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "62b258a8c95641a3072ab31662f3b8e5ba85de6dabf02c91af16065312fd14d3"

[versions]
forge = "47.3.5"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
