name = "Carnival of Horrors"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "52a403a8fc1ae597fa9939ec81dc0dea7b0c0bffe95c547fd761a61a6188127d"

[versions]
forge = "47.3.5"
minecraft = "1.20.1"
