name = "Clockwork Chronicles: Mystical Mechanics"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "52b49b3a08170944ec584ba2c0bee9e3b8eb511a3199aefef9e92c4d5bf53784"

[versions]
forge = "47.3.5"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
