name = "Carnival of Horrors"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5aa4a1a3e9d37c5fba69211ca1aa8dbad61f2f0ae69f706042b1b4953da3d943"

[versions]
forge = "47.3.5"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
