name = "Carnival of Horrors"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b6d76511ca8fa73ddcccc978866e7277fc624dcb0b58393540cf1309c677c1c3"

[versions]
forge = "47.3.5"
minecraft = "1.20.1"
