name = "Carnival of Horrors"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "51dc92611fcd0548094aa5c2bec5eb18468b58176d23fd5d6aa4bbc690a559d9"

[versions]
forge = "47.3.5"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
