name = "Clockwork Chronicles: Mystical Mechanics"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5c99ce48aa8f935e804caa8dcb108340d081281b0ec88d8db9946776a1130757"

[versions]
forge = "47.3.5"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
