name = "Carnival of Horrors"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2eafbd6d31465e474dcfa9c23696678471c28961a649259848d628f91013a8a7"

[versions]
forge = "47.3.5"
minecraft = "1.20.1"
