name = "Clockwork Chronicles: Mystical Mechanics"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2423f561ba406068197c795ee2b7fedb7c93e45af282ef80a0511c26b80cb1de"

[versions]
forge = "47.3.5"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
