name = "Clockwork Chronicles: Mystical Mechanics"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "059a77ac6b7cd3e584576140b75261b635ca508a1ff525651b5bc11f235abc8d"

[versions]
forge = "47.3.5"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
