
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 999999999
	#The name of the modpack
	modpackName = "Night at the Carnival"
	#The version of the modpack
	modpackVersion = "3.0.1"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

